/**
 * AI Disclaimer Page
 *
 * Communicates clearly what StudAI's AI features can and cannot do.
 * Linked from the footer and from AI-powered features.
 */

import { AlertTriangle } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";

export function AiDisclaimerPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <div className="container mx-auto px-4 py-12 flex-1">
        <div className="max-w-4xl mx-auto">
          <div className="flex items-center gap-3 mb-4">
            <AlertTriangle className="h-8 w-8 text-yellow-500 shrink-0" />
            <h1 className="text-4xl font-bold">AI Disclaimer</h1>
          </div>
          <p className="text-muted-foreground mb-8">Last updated: April 2026</p>

          {/* Legal review notice removed — content reviewed for launch */}

          <Card className="mb-6">
            <CardContent className="p-6 prose prose-sm max-w-none dark:prose-invert">
              <h2 className="text-xl font-bold mb-3">1. AI-Generated Content</h2>
              <p className="mb-4">
                StudAI uses artificial intelligence to help you study more effectively. AI-generated
                content — including study plans, explanations, quiz questions, flashcards, and
                recommendations — is provided for educational assistance only.
              </p>
              <p className="mb-4">
                AI-generated content may contain errors, inaccuracies, or outdated information.
                Always verify important information with authoritative sources, your instructor,
                or official study materials.
              </p>

              <h2 className="text-xl font-bold mb-3 mt-6">2. No Guarantee of Results</h2>
              <p className="mb-4">
                StudAI helps you organize and improve your study habits. We do not guarantee:
              </p>
              <ul className="list-disc pl-6 mb-4 space-y-1">
                <li>Specific exam scores or grades</li>
                <li>Passing any particular exam or certification</li>
                <li>Academic, professional, or career outcomes</li>
                <li>Accuracy of AI-generated explanations for all subjects</li>
              </ul>
              <p className="mb-4">
                Results depend on your individual effort, consistency, and study habits.
              </p>

              <h2 className="text-xl font-bold mb-3 mt-6">3. Not Professional Advice</h2>
              <p className="mb-4">
                Content generated by StudAI's AI is not a substitute for professional advice.
                Do not rely on StudAI for:
              </p>
              <ul className="list-disc pl-6 mb-4 space-y-1">
                <li>Medical or health decisions</li>
                <li>Legal advice</li>
                <li>Financial or investment decisions</li>
                <li>Official academic guidance from your institution</li>
              </ul>

              <h2 className="text-xl font-bold mb-3 mt-6">4. AI Limitations</h2>
              <p className="mb-4">
                Our AI assistant may occasionally:
              </p>
              <ul className="list-disc pl-6 mb-4 space-y-1">
                <li>Produce incorrect or incomplete answers ("hallucinations")</li>
                <li>Have limited knowledge of very recent events or publications</li>
                <li>Misunderstand ambiguous or highly specialized questions</li>
                <li>Provide different answers to the same question at different times</li>
              </ul>

              <h2 className="text-xl font-bold mb-3 mt-6">5. Your Responsibility</h2>
              <p className="mb-4">
                You are responsible for how you use AI-generated content. We encourage you to:
              </p>
              <ul className="list-disc pl-6 mb-4 space-y-1">
                <li>Cross-check important facts with official sources</li>
                <li>Use StudAI as a supplement to, not a replacement for, your study materials</li>
                <li>Report inaccurate or harmful AI output using the feedback feature</li>
              </ul>

              <h2 className="text-xl font-bold mb-3 mt-6">6. Feedback</h2>
              <p className="mb-4">
                If you encounter AI output that is incorrect, harmful, or inappropriate, please
                report it using the feedback button in the AI chat or contact us at{" "}
                <a href="mailto:support@studai.app" className="text-primary hover:underline">
                  support@studai.app
                </a>
                .
              </p>

              <h2 className="text-xl font-bold mb-3 mt-6">7. Changes</h2>
              <p className="mb-4">
                We may update this disclaimer as our AI features evolve. Continued use of
                StudAI after changes constitutes acceptance of the updated disclaimer.
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>
  );
}
