/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TrilhaRouteImport } from './routes/trilha'
import { Route as TrackCreateRouteImport } from './routes/track-create'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SupportRouteImport } from './routes/support'
import { Route as StudyRouteImport } from './routes/study'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SessoesRouteImport } from './routes/sessoes'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SearchTracksRouteImport } from './routes/search-tracks'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SalvosRouteImport } from './routes/salvos'
import { Route as RevisoesRouteImport } from './routes/revisoes'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as QuizzesRouteImport } from './routes/quizzes'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as ProgramasRouteImport } from './routes/programas'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PesquisarTrilhasRouteImport } from './routes/pesquisar-trilhas'
import { Route as PesquisarRouteImport } from './routes/pesquisar'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as MyTrackRouteImport } from './routes/my-track'
import { Route as MyPlanRouteImport } from './routes/my-plan'
import { Route as MyGoalRouteImport } from './routes/my-goal'
import { Route as MyCoursesRouteImport } from './routes/my-courses'
import { Route as ModuleCreateRouteImport } from './routes/module-create'
import { Route as ModuleRouteImport } from './routes/module'
import { Route as MeusCursosRouteImport } from './routes/meus-cursos'
import { Route as MeuPlanoRouteImport } from './routes/meu-plano'
import { Route as MeuObjetivoRouteImport } from './routes/meu-objetivo'
import { Route as MetricsRouteImport } from './routes/metrics'
import { Route as MetricasRouteImport } from './routes/metricas'
import { Route as LearningPreferencesRouteImport } from './routes/learning-preferences'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FavouritesRouteImport } from './routes/favourites'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ExplorarRouteImport } from './routes/explorar'
import { Route as EstudarRouteImport } from './routes/estudar'
import { Route as CriarTrilhaRouteImport } from './routes/criar-trilha'
import { Route as CriarCursoRouteImport } from './routes/criar-curso'
import { Route as CreateTrackRouteImport } from './routes/create-track'
import { Route as CreateCourseRouteImport } from './routes/create-course'
import { Route as ContentCreateRouteImport } from './routes/content-create'
import { Route as ContentRouteImport } from './routes/content'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as AvaliacoesRouteImport } from './routes/avaliacoes'
import { Route as AtividadeRouteImport } from './routes/atividade'
import { Route as AssessmentsRouteImport } from './routes/assessments'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackIndexRouteImport } from './routes/track/index'
import { Route as ModuleIndexRouteImport } from './routes/module/index'
import { Route as FavouritesIndexRouteImport } from './routes/favourites/index'
import { Route as ContentIndexRouteImport } from './routes/content/index'
import { Route as TrackTrackIdRouteImport } from './routes/track/$trackId'
import { Route as QuizQuizIdRouteImport } from './routes/quiz/$quizId'
import { Route as ModuleModuleIdRouteImport } from './routes/module/$moduleId'
import { Route as ModuleEditModuleIdRouteImport } from './routes/module-edit/$moduleId'
import { Route as ExploreTrackIdRouteImport } from './routes/explore/$trackId'
import { Route as ExplorarTrackIdRouteImport } from './routes/explorar/$trackId'
import { Route as CursoCourseIdRouteImport } from './routes/curso/$courseId'
import { Route as CourseCourseIdRouteImport } from './routes/course/$courseId'
import { Route as ContentContentIdRouteImport } from './routes/content/$contentId'
import { Route as TrackTrackIdIndexRouteImport } from './routes/track/$trackId/index'
import { Route as ModuleModuleIdIndexRouteImport } from './routes/module/$moduleId/index'
import { Route as ContentContentIdIndexRouteImport } from './routes/content/$contentId/index'
import { Route as TrackTrackIdEditRouteImport } from './routes/track/$trackId/edit'
import { Route as ContentContentIdEditRouteImport } from './routes/content/$contentId/edit'
import { Route as ModuleModuleIdContentContentIdRouteImport } from './routes/module/$moduleId/content/$contentId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TrilhaRoute = TrilhaRouteImport.update({
  id: '/trilha',
  path: '/trilha',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackCreateRoute = TrackCreateRouteImport.update({
  id: '/track-create',
  path: '/track-create',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SessoesRoute = SessoesRouteImport.update({
  id: '/sessoes',
  path: '/sessoes',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchTracksRoute = SearchTracksRouteImport.update({
  id: '/search-tracks',
  path: '/search-tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SalvosRoute = SalvosRouteImport.update({
  id: '/salvos',
  path: '/salvos',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisoesRoute = RevisoesRouteImport.update({
  id: '/revisoes',
  path: '/revisoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizzesRoute = QuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramasRoute = ProgramasRouteImport.update({
  id: '/programas',
  path: '/programas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisarTrilhasRoute = PesquisarTrilhasRouteImport.update({
  id: '/pesquisar-trilhas',
  path: '/pesquisar-trilhas',
  getParentRoute: () => rootRouteImport,
} as any)
const PesquisarRoute = PesquisarRouteImport.update({
  id: '/pesquisar',
  path: '/pesquisar',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTrackRoute = MyTrackRouteImport.update({
  id: '/my-track',
  path: '/my-track',
  getParentRoute: () => rootRouteImport,
} as any)
const MyPlanRoute = MyPlanRouteImport.update({
  id: '/my-plan',
  path: '/my-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const MyGoalRoute = MyGoalRouteImport.update({
  id: '/my-goal',
  path: '/my-goal',
  getParentRoute: () => rootRouteImport,
} as any)
const MyCoursesRoute = MyCoursesRouteImport.update({
  id: '/my-courses',
  path: '/my-courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleCreateRoute = ModuleCreateRouteImport.update({
  id: '/module-create',
  path: '/module-create',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleRoute = ModuleRouteImport.update({
  id: '/module',
  path: '/module',
  getParentRoute: () => rootRouteImport,
} as any)
const MeusCursosRoute = MeusCursosRouteImport.update({
  id: '/meus-cursos',
  path: '/meus-cursos',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuPlanoRoute = MeuPlanoRouteImport.update({
  id: '/meu-plano',
  path: '/meu-plano',
  getParentRoute: () => rootRouteImport,
} as any)
const MeuObjetivoRoute = MeuObjetivoRouteImport.update({
  id: '/meu-objetivo',
  path: '/meu-objetivo',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricsRoute = MetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const MetricasRoute = MetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => rootRouteImport,
} as any)
const LearningPreferencesRoute = LearningPreferencesRouteImport.update({
  id: '/learning-preferences',
  path: '/learning-preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouritesRoute = FavouritesRouteImport.update({
  id: '/favourites',
  path: '/favourites',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorarRoute = ExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudarRoute = EstudarRouteImport.update({
  id: '/estudar',
  path: '/estudar',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarTrilhaRoute = CriarTrilhaRouteImport.update({
  id: '/criar-trilha',
  path: '/criar-trilha',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarCursoRoute = CriarCursoRouteImport.update({
  id: '/criar-curso',
  path: '/criar-curso',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateTrackRoute = CreateTrackRouteImport.update({
  id: '/create-track',
  path: '/create-track',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateCourseRoute = CreateCourseRouteImport.update({
  id: '/create-course',
  path: '/create-course',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentCreateRoute = ContentCreateRouteImport.update({
  id: '/content-create',
  path: '/content-create',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AvaliacoesRoute = AvaliacoesRouteImport.update({
  id: '/avaliacoes',
  path: '/avaliacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AtividadeRoute = AtividadeRouteImport.update({
  id: '/atividade',
  path: '/atividade',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentsRoute = AssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIndexRoute = TrackIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrackRoute,
} as any)
const ModuleIndexRoute = ModuleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModuleRoute,
} as any)
const FavouritesIndexRoute = FavouritesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FavouritesRoute,
} as any)
const ContentIndexRoute = ContentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContentRoute,
} as any)
const TrackTrackIdRoute = TrackTrackIdRouteImport.update({
  id: '/$trackId',
  path: '/$trackId',
  getParentRoute: () => TrackRoute,
} as any)
const QuizQuizIdRoute = QuizQuizIdRouteImport.update({
  id: '/quiz/$quizId',
  path: '/quiz/$quizId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleModuleIdRoute = ModuleModuleIdRouteImport.update({
  id: '/$moduleId',
  path: '/$moduleId',
  getParentRoute: () => ModuleRoute,
} as any)
const ModuleEditModuleIdRoute = ModuleEditModuleIdRouteImport.update({
  id: '/module-edit/$moduleId',
  path: '/module-edit/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreTrackIdRoute = ExploreTrackIdRouteImport.update({
  id: '/$trackId',
  path: '/$trackId',
  getParentRoute: () => ExploreRoute,
} as any)
const ExplorarTrackIdRoute = ExplorarTrackIdRouteImport.update({
  id: '/$trackId',
  path: '/$trackId',
  getParentRoute: () => ExplorarRoute,
} as any)
const CursoCourseIdRoute = CursoCourseIdRouteImport.update({
  id: '/curso/$courseId',
  path: '/curso/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseCourseIdRoute = CourseCourseIdRouteImport.update({
  id: '/course/$courseId',
  path: '/course/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentContentIdRoute = ContentContentIdRouteImport.update({
  id: '/$contentId',
  path: '/$contentId',
  getParentRoute: () => ContentRoute,
} as any)
const TrackTrackIdIndexRoute = TrackTrackIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrackTrackIdRoute,
} as any)
const ModuleModuleIdIndexRoute = ModuleModuleIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModuleModuleIdRoute,
} as any)
const ContentContentIdIndexRoute = ContentContentIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContentContentIdRoute,
} as any)
const TrackTrackIdEditRoute = TrackTrackIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TrackTrackIdRoute,
} as any)
const ContentContentIdEditRoute = ContentContentIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ContentContentIdRoute,
} as any)
const ModuleModuleIdContentContentIdRoute =
  ModuleModuleIdContentContentIdRouteImport.update({
    id: '/content/$contentId',
    path: '/content/$contentId',
    getParentRoute: () => ModuleModuleIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/assessments': typeof AssessmentsRoute
  '/atividade': typeof AtividadeRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/calendar': typeof CalendarRoute
  '/calendario': typeof CalendarioRoute
  '/chat': typeof ChatRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRouteWithChildren
  '/content-create': typeof ContentCreateRoute
  '/create-course': typeof CreateCourseRoute
  '/create-track': typeof CreateTrackRoute
  '/criar-curso': typeof CriarCursoRoute
  '/criar-trilha': typeof CriarTrilhaRoute
  '/estudar': typeof EstudarRoute
  '/explorar': typeof ExplorarRouteWithChildren
  '/explore': typeof ExploreRouteWithChildren
  '/faq': typeof FaqRoute
  '/favourites': typeof FavouritesRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/learning-preferences': typeof LearningPreferencesRoute
  '/metricas': typeof MetricasRoute
  '/metrics': typeof MetricsRoute
  '/meu-objetivo': typeof MeuObjetivoRoute
  '/meu-plano': typeof MeuPlanoRoute
  '/meus-cursos': typeof MeusCursosRoute
  '/module': typeof ModuleRouteWithChildren
  '/module-create': typeof ModuleCreateRoute
  '/my-courses': typeof MyCoursesRoute
  '/my-goal': typeof MyGoalRoute
  '/my-plan': typeof MyPlanRoute
  '/my-track': typeof MyTrackRoute
  '/perfil': typeof PerfilRoute
  '/pesquisar': typeof PesquisarRoute
  '/pesquisar-trilhas': typeof PesquisarTrilhasRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/programas': typeof ProgramasRoute
  '/programs': typeof ProgramsRoute
  '/quizzes': typeof QuizzesRoute
  '/ranking': typeof RankingRoute
  '/relatorios': typeof RelatoriosRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/reviews': typeof ReviewsRoute
  '/revisoes': typeof RevisoesRoute
  '/salvos': typeof SalvosRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/search-tracks': typeof SearchTracksRoute
  '/security': typeof SecurityRoute
  '/sessions': typeof SessionsRoute
  '/sessoes': typeof SessoesRoute
  '/settings': typeof SettingsRoute
  '/sign-up': typeof SignUpRoute
  '/study': typeof StudyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRouteWithChildren
  '/track-create': typeof TrackCreateRoute
  '/trilha': typeof TrilhaRoute
  '/verify-email': typeof VerifyEmailRoute
  '/content/$contentId': typeof ContentContentIdRouteWithChildren
  '/course/$courseId': typeof CourseCourseIdRoute
  '/curso/$courseId': typeof CursoCourseIdRoute
  '/explorar/$trackId': typeof ExplorarTrackIdRoute
  '/explore/$trackId': typeof ExploreTrackIdRoute
  '/module-edit/$moduleId': typeof ModuleEditModuleIdRoute
  '/module/$moduleId': typeof ModuleModuleIdRouteWithChildren
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/track/$trackId': typeof TrackTrackIdRouteWithChildren
  '/content/': typeof ContentIndexRoute
  '/favourites/': typeof FavouritesIndexRoute
  '/module/': typeof ModuleIndexRoute
  '/track/': typeof TrackIndexRoute
  '/content/$contentId/edit': typeof ContentContentIdEditRoute
  '/track/$trackId/edit': typeof TrackTrackIdEditRoute
  '/content/$contentId/': typeof ContentContentIdIndexRoute
  '/module/$moduleId/': typeof ModuleModuleIdIndexRoute
  '/track/$trackId/': typeof TrackTrackIdIndexRoute
  '/module/$moduleId/content/$contentId': typeof ModuleModuleIdContentContentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/assessments': typeof AssessmentsRoute
  '/atividade': typeof AtividadeRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/calendar': typeof CalendarRoute
  '/calendario': typeof CalendarioRoute
  '/chat': typeof ChatRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contact': typeof ContactRoute
  '/content-create': typeof ContentCreateRoute
  '/create-course': typeof CreateCourseRoute
  '/create-track': typeof CreateTrackRoute
  '/criar-curso': typeof CriarCursoRoute
  '/criar-trilha': typeof CriarTrilhaRoute
  '/estudar': typeof EstudarRoute
  '/explorar': typeof ExplorarRouteWithChildren
  '/explore': typeof ExploreRouteWithChildren
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/learning-preferences': typeof LearningPreferencesRoute
  '/metricas': typeof MetricasRoute
  '/metrics': typeof MetricsRoute
  '/meu-objetivo': typeof MeuObjetivoRoute
  '/meu-plano': typeof MeuPlanoRoute
  '/meus-cursos': typeof MeusCursosRoute
  '/module-create': typeof ModuleCreateRoute
  '/my-courses': typeof MyCoursesRoute
  '/my-goal': typeof MyGoalRoute
  '/my-plan': typeof MyPlanRoute
  '/my-track': typeof MyTrackRoute
  '/perfil': typeof PerfilRoute
  '/pesquisar': typeof PesquisarRoute
  '/pesquisar-trilhas': typeof PesquisarTrilhasRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/programas': typeof ProgramasRoute
  '/programs': typeof ProgramsRoute
  '/quizzes': typeof QuizzesRoute
  '/ranking': typeof RankingRoute
  '/relatorios': typeof RelatoriosRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/reviews': typeof ReviewsRoute
  '/revisoes': typeof RevisoesRoute
  '/salvos': typeof SalvosRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/search-tracks': typeof SearchTracksRoute
  '/security': typeof SecurityRoute
  '/sessions': typeof SessionsRoute
  '/sessoes': typeof SessoesRoute
  '/settings': typeof SettingsRoute
  '/sign-up': typeof SignUpRoute
  '/study': typeof StudyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/track-create': typeof TrackCreateRoute
  '/trilha': typeof TrilhaRoute
  '/verify-email': typeof VerifyEmailRoute
  '/course/$courseId': typeof CourseCourseIdRoute
  '/curso/$courseId': typeof CursoCourseIdRoute
  '/explorar/$trackId': typeof ExplorarTrackIdRoute
  '/explore/$trackId': typeof ExploreTrackIdRoute
  '/module-edit/$moduleId': typeof ModuleEditModuleIdRoute
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/content': typeof ContentIndexRoute
  '/favourites': typeof FavouritesIndexRoute
  '/module': typeof ModuleIndexRoute
  '/track': typeof TrackIndexRoute
  '/content/$contentId/edit': typeof ContentContentIdEditRoute
  '/track/$trackId/edit': typeof TrackTrackIdEditRoute
  '/content/$contentId': typeof ContentContentIdIndexRoute
  '/module/$moduleId': typeof ModuleModuleIdIndexRoute
  '/track/$trackId': typeof TrackTrackIdIndexRoute
  '/module/$moduleId/content/$contentId': typeof ModuleModuleIdContentContentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/admin': typeof AdminRoute
  '/assessments': typeof AssessmentsRoute
  '/atividade': typeof AtividadeRoute
  '/avaliacoes': typeof AvaliacoesRoute
  '/calendar': typeof CalendarRoute
  '/calendario': typeof CalendarioRoute
  '/chat': typeof ChatRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/contact': typeof ContactRoute
  '/content': typeof ContentRouteWithChildren
  '/content-create': typeof ContentCreateRoute
  '/create-course': typeof CreateCourseRoute
  '/create-track': typeof CreateTrackRoute
  '/criar-curso': typeof CriarCursoRoute
  '/criar-trilha': typeof CriarTrilhaRoute
  '/estudar': typeof EstudarRoute
  '/explorar': typeof ExplorarRouteWithChildren
  '/explore': typeof ExploreRouteWithChildren
  '/faq': typeof FaqRoute
  '/favourites': typeof FavouritesRouteWithChildren
  '/how-it-works': typeof HowItWorksRoute
  '/learning-preferences': typeof LearningPreferencesRoute
  '/metricas': typeof MetricasRoute
  '/metrics': typeof MetricsRoute
  '/meu-objetivo': typeof MeuObjetivoRoute
  '/meu-plano': typeof MeuPlanoRoute
  '/meus-cursos': typeof MeusCursosRoute
  '/module': typeof ModuleRouteWithChildren
  '/module-create': typeof ModuleCreateRoute
  '/my-courses': typeof MyCoursesRoute
  '/my-goal': typeof MyGoalRoute
  '/my-plan': typeof MyPlanRoute
  '/my-track': typeof MyTrackRoute
  '/perfil': typeof PerfilRoute
  '/pesquisar': typeof PesquisarRoute
  '/pesquisar-trilhas': typeof PesquisarTrilhasRoute
  '/plans': typeof PlansRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/programas': typeof ProgramasRoute
  '/programs': typeof ProgramsRoute
  '/quizzes': typeof QuizzesRoute
  '/ranking': typeof RankingRoute
  '/relatorios': typeof RelatoriosRoute
  '/reports': typeof ReportsRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/reviews': typeof ReviewsRoute
  '/revisoes': typeof RevisoesRoute
  '/salvos': typeof SalvosRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/search-tracks': typeof SearchTracksRoute
  '/security': typeof SecurityRoute
  '/sessions': typeof SessionsRoute
  '/sessoes': typeof SessoesRoute
  '/settings': typeof SettingsRoute
  '/sign-up': typeof SignUpRoute
  '/study': typeof StudyRoute
  '/support': typeof SupportRoute
  '/terms': typeof TermsRoute
  '/track': typeof TrackRouteWithChildren
  '/track-create': typeof TrackCreateRoute
  '/trilha': typeof TrilhaRoute
  '/verify-email': typeof VerifyEmailRoute
  '/content/$contentId': typeof ContentContentIdRouteWithChildren
  '/course/$courseId': typeof CourseCourseIdRoute
  '/curso/$courseId': typeof CursoCourseIdRoute
  '/explorar/$trackId': typeof ExplorarTrackIdRoute
  '/explore/$trackId': typeof ExploreTrackIdRoute
  '/module-edit/$moduleId': typeof ModuleEditModuleIdRoute
  '/module/$moduleId': typeof ModuleModuleIdRouteWithChildren
  '/quiz/$quizId': typeof QuizQuizIdRoute
  '/track/$trackId': typeof TrackTrackIdRouteWithChildren
  '/content/': typeof ContentIndexRoute
  '/favourites/': typeof FavouritesIndexRoute
  '/module/': typeof ModuleIndexRoute
  '/track/': typeof TrackIndexRoute
  '/content/$contentId/edit': typeof ContentContentIdEditRoute
  '/track/$trackId/edit': typeof TrackTrackIdEditRoute
  '/content/$contentId/': typeof ContentContentIdIndexRoute
  '/module/$moduleId/': typeof ModuleModuleIdIndexRoute
  '/track/$trackId/': typeof TrackTrackIdIndexRoute
  '/module/$moduleId/content/$contentId': typeof ModuleModuleIdContentContentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/admin'
    | '/assessments'
    | '/atividade'
    | '/avaliacoes'
    | '/calendar'
    | '/calendario'
    | '/chat'
    | '/configuracoes'
    | '/contact'
    | '/content'
    | '/content-create'
    | '/create-course'
    | '/create-track'
    | '/criar-curso'
    | '/criar-trilha'
    | '/estudar'
    | '/explorar'
    | '/explore'
    | '/faq'
    | '/favourites'
    | '/how-it-works'
    | '/learning-preferences'
    | '/metricas'
    | '/metrics'
    | '/meu-objetivo'
    | '/meu-plano'
    | '/meus-cursos'
    | '/module'
    | '/module-create'
    | '/my-courses'
    | '/my-goal'
    | '/my-plan'
    | '/my-track'
    | '/perfil'
    | '/pesquisar'
    | '/pesquisar-trilhas'
    | '/plans'
    | '/privacy'
    | '/profile'
    | '/programas'
    | '/programs'
    | '/quizzes'
    | '/ranking'
    | '/relatorios'
    | '/reports'
    | '/reset-password'
    | '/resources'
    | '/reviews'
    | '/revisoes'
    | '/salvos'
    | '/saved'
    | '/search'
    | '/search-tracks'
    | '/security'
    | '/sessions'
    | '/sessoes'
    | '/settings'
    | '/sign-up'
    | '/study'
    | '/support'
    | '/terms'
    | '/track'
    | '/track-create'
    | '/trilha'
    | '/verify-email'
    | '/content/$contentId'
    | '/course/$courseId'
    | '/curso/$courseId'
    | '/explorar/$trackId'
    | '/explore/$trackId'
    | '/module-edit/$moduleId'
    | '/module/$moduleId'
    | '/quiz/$quizId'
    | '/track/$trackId'
    | '/content/'
    | '/favourites/'
    | '/module/'
    | '/track/'
    | '/content/$contentId/edit'
    | '/track/$trackId/edit'
    | '/content/$contentId/'
    | '/module/$moduleId/'
    | '/track/$trackId/'
    | '/module/$moduleId/content/$contentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/admin'
    | '/assessments'
    | '/atividade'
    | '/avaliacoes'
    | '/calendar'
    | '/calendario'
    | '/chat'
    | '/configuracoes'
    | '/contact'
    | '/content-create'
    | '/create-course'
    | '/create-track'
    | '/criar-curso'
    | '/criar-trilha'
    | '/estudar'
    | '/explorar'
    | '/explore'
    | '/faq'
    | '/how-it-works'
    | '/learning-preferences'
    | '/metricas'
    | '/metrics'
    | '/meu-objetivo'
    | '/meu-plano'
    | '/meus-cursos'
    | '/module-create'
    | '/my-courses'
    | '/my-goal'
    | '/my-plan'
    | '/my-track'
    | '/perfil'
    | '/pesquisar'
    | '/pesquisar-trilhas'
    | '/plans'
    | '/privacy'
    | '/profile'
    | '/programas'
    | '/programs'
    | '/quizzes'
    | '/ranking'
    | '/relatorios'
    | '/reports'
    | '/reset-password'
    | '/resources'
    | '/reviews'
    | '/revisoes'
    | '/salvos'
    | '/saved'
    | '/search'
    | '/search-tracks'
    | '/security'
    | '/sessions'
    | '/sessoes'
    | '/settings'
    | '/sign-up'
    | '/study'
    | '/support'
    | '/terms'
    | '/track-create'
    | '/trilha'
    | '/verify-email'
    | '/course/$courseId'
    | '/curso/$courseId'
    | '/explorar/$trackId'
    | '/explore/$trackId'
    | '/module-edit/$moduleId'
    | '/quiz/$quizId'
    | '/content'
    | '/favourites'
    | '/module'
    | '/track'
    | '/content/$contentId/edit'
    | '/track/$trackId/edit'
    | '/content/$contentId'
    | '/module/$moduleId'
    | '/track/$trackId'
    | '/module/$moduleId/content/$contentId'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/admin'
    | '/assessments'
    | '/atividade'
    | '/avaliacoes'
    | '/calendar'
    | '/calendario'
    | '/chat'
    | '/configuracoes'
    | '/contact'
    | '/content'
    | '/content-create'
    | '/create-course'
    | '/create-track'
    | '/criar-curso'
    | '/criar-trilha'
    | '/estudar'
    | '/explorar'
    | '/explore'
    | '/faq'
    | '/favourites'
    | '/how-it-works'
    | '/learning-preferences'
    | '/metricas'
    | '/metrics'
    | '/meu-objetivo'
    | '/meu-plano'
    | '/meus-cursos'
    | '/module'
    | '/module-create'
    | '/my-courses'
    | '/my-goal'
    | '/my-plan'
    | '/my-track'
    | '/perfil'
    | '/pesquisar'
    | '/pesquisar-trilhas'
    | '/plans'
    | '/privacy'
    | '/profile'
    | '/programas'
    | '/programs'
    | '/quizzes'
    | '/ranking'
    | '/relatorios'
    | '/reports'
    | '/reset-password'
    | '/resources'
    | '/reviews'
    | '/revisoes'
    | '/salvos'
    | '/saved'
    | '/search'
    | '/search-tracks'
    | '/security'
    | '/sessions'
    | '/sessoes'
    | '/settings'
    | '/sign-up'
    | '/study'
    | '/support'
    | '/terms'
    | '/track'
    | '/track-create'
    | '/trilha'
    | '/verify-email'
    | '/content/$contentId'
    | '/course/$courseId'
    | '/curso/$courseId'
    | '/explorar/$trackId'
    | '/explore/$trackId'
    | '/module-edit/$moduleId'
    | '/module/$moduleId'
    | '/quiz/$quizId'
    | '/track/$trackId'
    | '/content/'
    | '/favourites/'
    | '/module/'
    | '/track/'
    | '/content/$contentId/edit'
    | '/track/$trackId/edit'
    | '/content/$contentId/'
    | '/module/$moduleId/'
    | '/track/$trackId/'
    | '/module/$moduleId/content/$contentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AdminRoute: typeof AdminRoute
  AssessmentsRoute: typeof AssessmentsRoute
  AtividadeRoute: typeof AtividadeRoute
  AvaliacoesRoute: typeof AvaliacoesRoute
  CalendarRoute: typeof CalendarRoute
  CalendarioRoute: typeof CalendarioRoute
  ChatRoute: typeof ChatRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  ContactRoute: typeof ContactRoute
  ContentRoute: typeof ContentRouteWithChildren
  ContentCreateRoute: typeof ContentCreateRoute
  CreateCourseRoute: typeof CreateCourseRoute
  CreateTrackRoute: typeof CreateTrackRoute
  CriarCursoRoute: typeof CriarCursoRoute
  CriarTrilhaRoute: typeof CriarTrilhaRoute
  EstudarRoute: typeof EstudarRoute
  ExplorarRoute: typeof ExplorarRouteWithChildren
  ExploreRoute: typeof ExploreRouteWithChildren
  FaqRoute: typeof FaqRoute
  FavouritesRoute: typeof FavouritesRouteWithChildren
  HowItWorksRoute: typeof HowItWorksRoute
  LearningPreferencesRoute: typeof LearningPreferencesRoute
  MetricasRoute: typeof MetricasRoute
  MetricsRoute: typeof MetricsRoute
  MeuObjetivoRoute: typeof MeuObjetivoRoute
  MeuPlanoRoute: typeof MeuPlanoRoute
  MeusCursosRoute: typeof MeusCursosRoute
  ModuleRoute: typeof ModuleRouteWithChildren
  ModuleCreateRoute: typeof ModuleCreateRoute
  MyCoursesRoute: typeof MyCoursesRoute
  MyGoalRoute: typeof MyGoalRoute
  MyPlanRoute: typeof MyPlanRoute
  MyTrackRoute: typeof MyTrackRoute
  PerfilRoute: typeof PerfilRoute
  PesquisarRoute: typeof PesquisarRoute
  PesquisarTrilhasRoute: typeof PesquisarTrilhasRoute
  PlansRoute: typeof PlansRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  ProgramasRoute: typeof ProgramasRoute
  ProgramsRoute: typeof ProgramsRoute
  QuizzesRoute: typeof QuizzesRoute
  RankingRoute: typeof RankingRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ReportsRoute: typeof ReportsRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  ReviewsRoute: typeof ReviewsRoute
  RevisoesRoute: typeof RevisoesRoute
  SalvosRoute: typeof SalvosRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  SearchTracksRoute: typeof SearchTracksRoute
  SecurityRoute: typeof SecurityRoute
  SessionsRoute: typeof SessionsRoute
  SessoesRoute: typeof SessoesRoute
  SettingsRoute: typeof SettingsRoute
  SignUpRoute: typeof SignUpRoute
  StudyRoute: typeof StudyRoute
  SupportRoute: typeof SupportRoute
  TermsRoute: typeof TermsRoute
  TrackRoute: typeof TrackRouteWithChildren
  TrackCreateRoute: typeof TrackCreateRoute
  TrilhaRoute: typeof TrilhaRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  CourseCourseIdRoute: typeof CourseCourseIdRoute
  CursoCourseIdRoute: typeof CursoCourseIdRoute
  ModuleEditModuleIdRoute: typeof ModuleEditModuleIdRoute
  QuizQuizIdRoute: typeof QuizQuizIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trilha': {
      id: '/trilha'
      path: '/trilha'
      fullPath: '/trilha'
      preLoaderRoute: typeof TrilhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-create': {
      id: '/track-create'
      path: '/track-create'
      fullPath: '/track-create'
      preLoaderRoute: typeof TrackCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessoes': {
      id: '/sessoes'
      path: '/sessoes'
      fullPath: '/sessoes'
      preLoaderRoute: typeof SessoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search-tracks': {
      id: '/search-tracks'
      path: '/search-tracks'
      fullPath: '/search-tracks'
      preLoaderRoute: typeof SearchTracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/salvos': {
      id: '/salvos'
      path: '/salvos'
      fullPath: '/salvos'
      preLoaderRoute: typeof SalvosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisoes': {
      id: '/revisoes'
      path: '/revisoes'
      fullPath: '/revisoes'
      preLoaderRoute: typeof RevisoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quizzes': {
      id: '/quizzes'
      path: '/quizzes'
      fullPath: '/quizzes'
      preLoaderRoute: typeof QuizzesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programas': {
      id: '/programas'
      path: '/programas'
      fullPath: '/programas'
      preLoaderRoute: typeof ProgramasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisar-trilhas': {
      id: '/pesquisar-trilhas'
      path: '/pesquisar-trilhas'
      fullPath: '/pesquisar-trilhas'
      preLoaderRoute: typeof PesquisarTrilhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesquisar': {
      id: '/pesquisar'
      path: '/pesquisar'
      fullPath: '/pesquisar'
      preLoaderRoute: typeof PesquisarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-track': {
      id: '/my-track'
      path: '/my-track'
      fullPath: '/my-track'
      preLoaderRoute: typeof MyTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-plan': {
      id: '/my-plan'
      path: '/my-plan'
      fullPath: '/my-plan'
      preLoaderRoute: typeof MyPlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-goal': {
      id: '/my-goal'
      path: '/my-goal'
      fullPath: '/my-goal'
      preLoaderRoute: typeof MyGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-courses': {
      id: '/my-courses'
      path: '/my-courses'
      fullPath: '/my-courses'
      preLoaderRoute: typeof MyCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/module-create': {
      id: '/module-create'
      path: '/module-create'
      fullPath: '/module-create'
      preLoaderRoute: typeof ModuleCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/module': {
      id: '/module'
      path: '/module'
      fullPath: '/module'
      preLoaderRoute: typeof ModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meus-cursos': {
      id: '/meus-cursos'
      path: '/meus-cursos'
      fullPath: '/meus-cursos'
      preLoaderRoute: typeof MeusCursosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-plano': {
      id: '/meu-plano'
      path: '/meu-plano'
      fullPath: '/meu-plano'
      preLoaderRoute: typeof MeuPlanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meu-objetivo': {
      id: '/meu-objetivo'
      path: '/meu-objetivo'
      fullPath: '/meu-objetivo'
      preLoaderRoute: typeof MeuObjetivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metrics': {
      id: '/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof MetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metricas': {
      id: '/metricas'
      path: '/metricas'
      fullPath: '/metricas'
      preLoaderRoute: typeof MetricasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learning-preferences': {
      id: '/learning-preferences'
      path: '/learning-preferences'
      fullPath: '/learning-preferences'
      preLoaderRoute: typeof LearningPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourites': {
      id: '/favourites'
      path: '/favourites'
      fullPath: '/favourites'
      preLoaderRoute: typeof FavouritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorar': {
      id: '/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof ExplorarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudar': {
      id: '/estudar'
      path: '/estudar'
      fullPath: '/estudar'
      preLoaderRoute: typeof EstudarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-trilha': {
      id: '/criar-trilha'
      path: '/criar-trilha'
      fullPath: '/criar-trilha'
      preLoaderRoute: typeof CriarTrilhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-curso': {
      id: '/criar-curso'
      path: '/criar-curso'
      fullPath: '/criar-curso'
      preLoaderRoute: typeof CriarCursoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-track': {
      id: '/create-track'
      path: '/create-track'
      fullPath: '/create-track'
      preLoaderRoute: typeof CreateTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-course': {
      id: '/create-course'
      path: '/create-course'
      fullPath: '/create-course'
      preLoaderRoute: typeof CreateCourseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-create': {
      id: '/content-create'
      path: '/content-create'
      fullPath: '/content-create'
      preLoaderRoute: typeof ContentCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/avaliacoes': {
      id: '/avaliacoes'
      path: '/avaliacoes'
      fullPath: '/avaliacoes'
      preLoaderRoute: typeof AvaliacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atividade': {
      id: '/atividade'
      path: '/atividade'
      fullPath: '/atividade'
      preLoaderRoute: typeof AtividadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessments': {
      id: '/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/': {
      id: '/track/'
      path: '/'
      fullPath: '/track/'
      preLoaderRoute: typeof TrackIndexRouteImport
      parentRoute: typeof TrackRoute
    }
    '/module/': {
      id: '/module/'
      path: '/'
      fullPath: '/module/'
      preLoaderRoute: typeof ModuleIndexRouteImport
      parentRoute: typeof ModuleRoute
    }
    '/favourites/': {
      id: '/favourites/'
      path: '/'
      fullPath: '/favourites/'
      preLoaderRoute: typeof FavouritesIndexRouteImport
      parentRoute: typeof FavouritesRoute
    }
    '/content/': {
      id: '/content/'
      path: '/'
      fullPath: '/content/'
      preLoaderRoute: typeof ContentIndexRouteImport
      parentRoute: typeof ContentRoute
    }
    '/track/$trackId': {
      id: '/track/$trackId'
      path: '/$trackId'
      fullPath: '/track/$trackId'
      preLoaderRoute: typeof TrackTrackIdRouteImport
      parentRoute: typeof TrackRoute
    }
    '/quiz/$quizId': {
      id: '/quiz/$quizId'
      path: '/quiz/$quizId'
      fullPath: '/quiz/$quizId'
      preLoaderRoute: typeof QuizQuizIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/module/$moduleId': {
      id: '/module/$moduleId'
      path: '/$moduleId'
      fullPath: '/module/$moduleId'
      preLoaderRoute: typeof ModuleModuleIdRouteImport
      parentRoute: typeof ModuleRoute
    }
    '/module-edit/$moduleId': {
      id: '/module-edit/$moduleId'
      path: '/module-edit/$moduleId'
      fullPath: '/module-edit/$moduleId'
      preLoaderRoute: typeof ModuleEditModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore/$trackId': {
      id: '/explore/$trackId'
      path: '/$trackId'
      fullPath: '/explore/$trackId'
      preLoaderRoute: typeof ExploreTrackIdRouteImport
      parentRoute: typeof ExploreRoute
    }
    '/explorar/$trackId': {
      id: '/explorar/$trackId'
      path: '/$trackId'
      fullPath: '/explorar/$trackId'
      preLoaderRoute: typeof ExplorarTrackIdRouteImport
      parentRoute: typeof ExplorarRoute
    }
    '/curso/$courseId': {
      id: '/curso/$courseId'
      path: '/curso/$courseId'
      fullPath: '/curso/$courseId'
      preLoaderRoute: typeof CursoCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/course/$courseId': {
      id: '/course/$courseId'
      path: '/course/$courseId'
      fullPath: '/course/$courseId'
      preLoaderRoute: typeof CourseCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$contentId': {
      id: '/content/$contentId'
      path: '/$contentId'
      fullPath: '/content/$contentId'
      preLoaderRoute: typeof ContentContentIdRouteImport
      parentRoute: typeof ContentRoute
    }
    '/track/$trackId/': {
      id: '/track/$trackId/'
      path: '/'
      fullPath: '/track/$trackId/'
      preLoaderRoute: typeof TrackTrackIdIndexRouteImport
      parentRoute: typeof TrackTrackIdRoute
    }
    '/module/$moduleId/': {
      id: '/module/$moduleId/'
      path: '/'
      fullPath: '/module/$moduleId/'
      preLoaderRoute: typeof ModuleModuleIdIndexRouteImport
      parentRoute: typeof ModuleModuleIdRoute
    }
    '/content/$contentId/': {
      id: '/content/$contentId/'
      path: '/'
      fullPath: '/content/$contentId/'
      preLoaderRoute: typeof ContentContentIdIndexRouteImport
      parentRoute: typeof ContentContentIdRoute
    }
    '/track/$trackId/edit': {
      id: '/track/$trackId/edit'
      path: '/edit'
      fullPath: '/track/$trackId/edit'
      preLoaderRoute: typeof TrackTrackIdEditRouteImport
      parentRoute: typeof TrackTrackIdRoute
    }
    '/content/$contentId/edit': {
      id: '/content/$contentId/edit'
      path: '/edit'
      fullPath: '/content/$contentId/edit'
      preLoaderRoute: typeof ContentContentIdEditRouteImport
      parentRoute: typeof ContentContentIdRoute
    }
    '/module/$moduleId/content/$contentId': {
      id: '/module/$moduleId/content/$contentId'
      path: '/content/$contentId'
      fullPath: '/module/$moduleId/content/$contentId'
      preLoaderRoute: typeof ModuleModuleIdContentContentIdRouteImport
      parentRoute: typeof ModuleModuleIdRoute
    }
  }
}

interface ContentContentIdRouteChildren {
  ContentContentIdEditRoute: typeof ContentContentIdEditRoute
  ContentContentIdIndexRoute: typeof ContentContentIdIndexRoute
}

const ContentContentIdRouteChildren: ContentContentIdRouteChildren = {
  ContentContentIdEditRoute: ContentContentIdEditRoute,
  ContentContentIdIndexRoute: ContentContentIdIndexRoute,
}

const ContentContentIdRouteWithChildren =
  ContentContentIdRoute._addFileChildren(ContentContentIdRouteChildren)

interface ContentRouteChildren {
  ContentContentIdRoute: typeof ContentContentIdRouteWithChildren
  ContentIndexRoute: typeof ContentIndexRoute
}

const ContentRouteChildren: ContentRouteChildren = {
  ContentContentIdRoute: ContentContentIdRouteWithChildren,
  ContentIndexRoute: ContentIndexRoute,
}

const ContentRouteWithChildren =
  ContentRoute._addFileChildren(ContentRouteChildren)

interface ExplorarRouteChildren {
  ExplorarTrackIdRoute: typeof ExplorarTrackIdRoute
}

const ExplorarRouteChildren: ExplorarRouteChildren = {
  ExplorarTrackIdRoute: ExplorarTrackIdRoute,
}

const ExplorarRouteWithChildren = ExplorarRoute._addFileChildren(
  ExplorarRouteChildren,
)

interface ExploreRouteChildren {
  ExploreTrackIdRoute: typeof ExploreTrackIdRoute
}

const ExploreRouteChildren: ExploreRouteChildren = {
  ExploreTrackIdRoute: ExploreTrackIdRoute,
}

const ExploreRouteWithChildren =
  ExploreRoute._addFileChildren(ExploreRouteChildren)

interface FavouritesRouteChildren {
  FavouritesIndexRoute: typeof FavouritesIndexRoute
}

const FavouritesRouteChildren: FavouritesRouteChildren = {
  FavouritesIndexRoute: FavouritesIndexRoute,
}

const FavouritesRouteWithChildren = FavouritesRoute._addFileChildren(
  FavouritesRouteChildren,
)

interface ModuleModuleIdRouteChildren {
  ModuleModuleIdIndexRoute: typeof ModuleModuleIdIndexRoute
  ModuleModuleIdContentContentIdRoute: typeof ModuleModuleIdContentContentIdRoute
}

const ModuleModuleIdRouteChildren: ModuleModuleIdRouteChildren = {
  ModuleModuleIdIndexRoute: ModuleModuleIdIndexRoute,
  ModuleModuleIdContentContentIdRoute: ModuleModuleIdContentContentIdRoute,
}

const ModuleModuleIdRouteWithChildren = ModuleModuleIdRoute._addFileChildren(
  ModuleModuleIdRouteChildren,
)

interface ModuleRouteChildren {
  ModuleModuleIdRoute: typeof ModuleModuleIdRouteWithChildren
  ModuleIndexRoute: typeof ModuleIndexRoute
}

const ModuleRouteChildren: ModuleRouteChildren = {
  ModuleModuleIdRoute: ModuleModuleIdRouteWithChildren,
  ModuleIndexRoute: ModuleIndexRoute,
}

const ModuleRouteWithChildren =
  ModuleRoute._addFileChildren(ModuleRouteChildren)

interface TrackTrackIdRouteChildren {
  TrackTrackIdEditRoute: typeof TrackTrackIdEditRoute
  TrackTrackIdIndexRoute: typeof TrackTrackIdIndexRoute
}

const TrackTrackIdRouteChildren: TrackTrackIdRouteChildren = {
  TrackTrackIdEditRoute: TrackTrackIdEditRoute,
  TrackTrackIdIndexRoute: TrackTrackIdIndexRoute,
}

const TrackTrackIdRouteWithChildren = TrackTrackIdRoute._addFileChildren(
  TrackTrackIdRouteChildren,
)

interface TrackRouteChildren {
  TrackTrackIdRoute: typeof TrackTrackIdRouteWithChildren
  TrackIndexRoute: typeof TrackIndexRoute
}

const TrackRouteChildren: TrackRouteChildren = {
  TrackTrackIdRoute: TrackTrackIdRouteWithChildren,
  TrackIndexRoute: TrackIndexRoute,
}

const TrackRouteWithChildren = TrackRoute._addFileChildren(TrackRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AdminRoute: AdminRoute,
  AssessmentsRoute: AssessmentsRoute,
  AtividadeRoute: AtividadeRoute,
  AvaliacoesRoute: AvaliacoesRoute,
  CalendarRoute: CalendarRoute,
  CalendarioRoute: CalendarioRoute,
  ChatRoute: ChatRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  ContactRoute: ContactRoute,
  ContentRoute: ContentRouteWithChildren,
  ContentCreateRoute: ContentCreateRoute,
  CreateCourseRoute: CreateCourseRoute,
  CreateTrackRoute: CreateTrackRoute,
  CriarCursoRoute: CriarCursoRoute,
  CriarTrilhaRoute: CriarTrilhaRoute,
  EstudarRoute: EstudarRoute,
  ExplorarRoute: ExplorarRouteWithChildren,
  ExploreRoute: ExploreRouteWithChildren,
  FaqRoute: FaqRoute,
  FavouritesRoute: FavouritesRouteWithChildren,
  HowItWorksRoute: HowItWorksRoute,
  LearningPreferencesRoute: LearningPreferencesRoute,
  MetricasRoute: MetricasRoute,
  MetricsRoute: MetricsRoute,
  MeuObjetivoRoute: MeuObjetivoRoute,
  MeuPlanoRoute: MeuPlanoRoute,
  MeusCursosRoute: MeusCursosRoute,
  ModuleRoute: ModuleRouteWithChildren,
  ModuleCreateRoute: ModuleCreateRoute,
  MyCoursesRoute: MyCoursesRoute,
  MyGoalRoute: MyGoalRoute,
  MyPlanRoute: MyPlanRoute,
  MyTrackRoute: MyTrackRoute,
  PerfilRoute: PerfilRoute,
  PesquisarRoute: PesquisarRoute,
  PesquisarTrilhasRoute: PesquisarTrilhasRoute,
  PlansRoute: PlansRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  ProgramasRoute: ProgramasRoute,
  ProgramsRoute: ProgramsRoute,
  QuizzesRoute: QuizzesRoute,
  RankingRoute: RankingRoute,
  RelatoriosRoute: RelatoriosRoute,
  ReportsRoute: ReportsRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  ReviewsRoute: ReviewsRoute,
  RevisoesRoute: RevisoesRoute,
  SalvosRoute: SalvosRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  SearchTracksRoute: SearchTracksRoute,
  SecurityRoute: SecurityRoute,
  SessionsRoute: SessionsRoute,
  SessoesRoute: SessoesRoute,
  SettingsRoute: SettingsRoute,
  SignUpRoute: SignUpRoute,
  StudyRoute: StudyRoute,
  SupportRoute: SupportRoute,
  TermsRoute: TermsRoute,
  TrackRoute: TrackRouteWithChildren,
  TrackCreateRoute: TrackCreateRoute,
  TrilhaRoute: TrilhaRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  CourseCourseIdRoute: CourseCourseIdRoute,
  CursoCourseIdRoute: CursoCourseIdRoute,
  ModuleEditModuleIdRoute: ModuleEditModuleIdRoute,
  QuizQuizIdRoute: QuizQuizIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
