/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TrackCreateRouteImport } from './routes/track-create'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ModuleCreateRouteImport } from './routes/module-create'
import { Route as ModuleRouteImport } from './routes/module'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContentEditRouteImport } from './routes/content-edit'
import { Route as ContentCreateRouteImport } from './routes/content-create'
import { Route as ContentRouteImport } from './routes/content'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackIndexRouteImport } from './routes/track/index'
import { Route as ModuleIndexRouteImport } from './routes/module/index'
import { Route as ContentIndexRouteImport } from './routes/content/index'
import { Route as TrackTrackIdRouteImport } from './routes/track/$trackId'
import { Route as TrackEditTrackIdRouteImport } from './routes/track-edit/$trackId'
import { Route as ModuleModuleIdRouteImport } from './routes/module/$moduleId'
import { Route as ModuleEditModuleIdRouteImport } from './routes/module-edit/$moduleId'
import { Route as ContentContentIdRouteImport } from './routes/content/$contentId'
import { Route as TrackTrackIdIndexRouteImport } from './routes/track/$trackId/index'
import { Route as ModuleModuleIdIndexRouteImport } from './routes/module/$moduleId/index'
import { Route as ContentContentIdIndexRouteImport } from './routes/content/$contentId/index'
import { Route as ContentContentIdEditRouteImport } from './routes/content/$contentId/edit'
import { Route as ModuleModuleIdContentContentIdRouteImport } from './routes/module/$moduleId/content/$contentId'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackCreateRoute = TrackCreateRouteImport.update({
  id: '/track-create',
  path: '/track-create',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleCreateRoute = ModuleCreateRouteImport.update({
  id: '/module-create',
  path: '/module-create',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleRoute = ModuleRouteImport.update({
  id: '/module',
  path: '/module',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentEditRoute = ContentEditRouteImport.update({
  id: '/content-edit',
  path: '/content-edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentCreateRoute = ContentCreateRouteImport.update({
  id: '/content-create',
  path: '/content-create',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIndexRoute = TrackIndexRouteImport.update({
  id: '/track/',
  path: '/track/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleIndexRoute = ModuleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModuleRoute,
} as any)
const ContentIndexRoute = ContentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContentRoute,
} as any)
const TrackTrackIdRoute = TrackTrackIdRouteImport.update({
  id: '/track/$trackId',
  path: '/track/$trackId',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackEditTrackIdRoute = TrackEditTrackIdRouteImport.update({
  id: '/track-edit/$trackId',
  path: '/track-edit/$trackId',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleModuleIdRoute = ModuleModuleIdRouteImport.update({
  id: '/$moduleId',
  path: '/$moduleId',
  getParentRoute: () => ModuleRoute,
} as any)
const ModuleEditModuleIdRoute = ModuleEditModuleIdRouteImport.update({
  id: '/module-edit/$moduleId',
  path: '/module-edit/$moduleId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentContentIdRoute = ContentContentIdRouteImport.update({
  id: '/$contentId',
  path: '/$contentId',
  getParentRoute: () => ContentRoute,
} as any)
const TrackTrackIdIndexRoute = TrackTrackIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrackTrackIdRoute,
} as any)
const ModuleModuleIdIndexRoute = ModuleModuleIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ModuleModuleIdRoute,
} as any)
const ContentContentIdIndexRoute = ContentContentIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContentContentIdRoute,
} as any)
const ContentContentIdEditRoute = ContentContentIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ContentContentIdRoute,
} as any)
const ModuleModuleIdContentContentIdRoute =
  ModuleModuleIdContentContentIdRouteImport.update({
    id: '/content/$contentId',
    path: '/content/$contentId',
    getParentRoute: () => ModuleModuleIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/content': typeof ContentRouteWithChildren
  '/content-create': typeof ContentCreateRoute
  '/content-edit': typeof ContentEditRoute
  '/dashboard': typeof DashboardRoute
  '/module': typeof ModuleRouteWithChildren
  '/module-create': typeof ModuleCreateRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-up': typeof SignUpRoute
  '/track-create': typeof TrackCreateRoute
  '/verify-email': typeof VerifyEmailRoute
  '/content/$contentId': typeof ContentContentIdRouteWithChildren
  '/module-edit/$moduleId': typeof ModuleEditModuleIdRoute
  '/module/$moduleId': typeof ModuleModuleIdRouteWithChildren
  '/track-edit/$trackId': typeof TrackEditTrackIdRoute
  '/track/$trackId': typeof TrackTrackIdRouteWithChildren
  '/content/': typeof ContentIndexRoute
  '/module/': typeof ModuleIndexRoute
  '/track/': typeof TrackIndexRoute
  '/content/$contentId/edit': typeof ContentContentIdEditRoute
  '/content/$contentId/': typeof ContentContentIdIndexRoute
  '/module/$moduleId/': typeof ModuleModuleIdIndexRoute
  '/track/$trackId/': typeof TrackTrackIdIndexRoute
  '/module/$moduleId/content/$contentId': typeof ModuleModuleIdContentContentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/content-create': typeof ContentCreateRoute
  '/content-edit': typeof ContentEditRoute
  '/dashboard': typeof DashboardRoute
  '/module-create': typeof ModuleCreateRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-up': typeof SignUpRoute
  '/track-create': typeof TrackCreateRoute
  '/verify-email': typeof VerifyEmailRoute
  '/module-edit/$moduleId': typeof ModuleEditModuleIdRoute
  '/track-edit/$trackId': typeof TrackEditTrackIdRoute
  '/content': typeof ContentIndexRoute
  '/module': typeof ModuleIndexRoute
  '/track': typeof TrackIndexRoute
  '/content/$contentId/edit': typeof ContentContentIdEditRoute
  '/content/$contentId': typeof ContentContentIdIndexRoute
  '/module/$moduleId': typeof ModuleModuleIdIndexRoute
  '/track/$trackId': typeof TrackTrackIdIndexRoute
  '/module/$moduleId/content/$contentId': typeof ModuleModuleIdContentContentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/content': typeof ContentRouteWithChildren
  '/content-create': typeof ContentCreateRoute
  '/content-edit': typeof ContentEditRoute
  '/dashboard': typeof DashboardRoute
  '/module': typeof ModuleRouteWithChildren
  '/module-create': typeof ModuleCreateRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sign-up': typeof SignUpRoute
  '/track-create': typeof TrackCreateRoute
  '/verify-email': typeof VerifyEmailRoute
  '/content/$contentId': typeof ContentContentIdRouteWithChildren
  '/module-edit/$moduleId': typeof ModuleEditModuleIdRoute
  '/module/$moduleId': typeof ModuleModuleIdRouteWithChildren
  '/track-edit/$trackId': typeof TrackEditTrackIdRoute
  '/track/$trackId': typeof TrackTrackIdRouteWithChildren
  '/content/': typeof ContentIndexRoute
  '/module/': typeof ModuleIndexRoute
  '/track/': typeof TrackIndexRoute
  '/content/$contentId/edit': typeof ContentContentIdEditRoute
  '/content/$contentId/': typeof ContentContentIdIndexRoute
  '/module/$moduleId/': typeof ModuleModuleIdIndexRoute
  '/track/$trackId/': typeof TrackTrackIdIndexRoute
  '/module/$moduleId/content/$contentId': typeof ModuleModuleIdContentContentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/content'
    | '/content-create'
    | '/content-edit'
    | '/dashboard'
    | '/module'
    | '/module-create'
    | '/reset-password'
    | '/sign-up'
    | '/track-create'
    | '/verify-email'
    | '/content/$contentId'
    | '/module-edit/$moduleId'
    | '/module/$moduleId'
    | '/track-edit/$trackId'
    | '/track/$trackId'
    | '/content/'
    | '/module/'
    | '/track/'
    | '/content/$contentId/edit'
    | '/content/$contentId/'
    | '/module/$moduleId/'
    | '/track/$trackId/'
    | '/module/$moduleId/content/$contentId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/content-create'
    | '/content-edit'
    | '/dashboard'
    | '/module-create'
    | '/reset-password'
    | '/sign-up'
    | '/track-create'
    | '/verify-email'
    | '/module-edit/$moduleId'
    | '/track-edit/$trackId'
    | '/content'
    | '/module'
    | '/track'
    | '/content/$contentId/edit'
    | '/content/$contentId'
    | '/module/$moduleId'
    | '/track/$trackId'
    | '/module/$moduleId/content/$contentId'
  id:
    | '__root__'
    | '/'
    | '/content'
    | '/content-create'
    | '/content-edit'
    | '/dashboard'
    | '/module'
    | '/module-create'
    | '/reset-password'
    | '/sign-up'
    | '/track-create'
    | '/verify-email'
    | '/content/$contentId'
    | '/module-edit/$moduleId'
    | '/module/$moduleId'
    | '/track-edit/$trackId'
    | '/track/$trackId'
    | '/content/'
    | '/module/'
    | '/track/'
    | '/content/$contentId/edit'
    | '/content/$contentId/'
    | '/module/$moduleId/'
    | '/track/$trackId/'
    | '/module/$moduleId/content/$contentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContentRoute: typeof ContentRouteWithChildren
  ContentCreateRoute: typeof ContentCreateRoute
  ContentEditRoute: typeof ContentEditRoute
  DashboardRoute: typeof DashboardRoute
  ModuleRoute: typeof ModuleRouteWithChildren
  ModuleCreateRoute: typeof ModuleCreateRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignUpRoute: typeof SignUpRoute
  TrackCreateRoute: typeof TrackCreateRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  ModuleEditModuleIdRoute: typeof ModuleEditModuleIdRoute
  TrackEditTrackIdRoute: typeof TrackEditTrackIdRoute
  TrackTrackIdRoute: typeof TrackTrackIdRouteWithChildren
  TrackIndexRoute: typeof TrackIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-create': {
      id: '/track-create'
      path: '/track-create'
      fullPath: '/track-create'
      preLoaderRoute: typeof TrackCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/module-create': {
      id: '/module-create'
      path: '/module-create'
      fullPath: '/module-create'
      preLoaderRoute: typeof ModuleCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/module': {
      id: '/module'
      path: '/module'
      fullPath: '/module'
      preLoaderRoute: typeof ModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-edit': {
      id: '/content-edit'
      path: '/content-edit'
      fullPath: '/content-edit'
      preLoaderRoute: typeof ContentEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content-create': {
      id: '/content-create'
      path: '/content-create'
      fullPath: '/content-create'
      preLoaderRoute: typeof ContentCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/': {
      id: '/track/'
      path: '/track'
      fullPath: '/track/'
      preLoaderRoute: typeof TrackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/module/': {
      id: '/module/'
      path: '/'
      fullPath: '/module/'
      preLoaderRoute: typeof ModuleIndexRouteImport
      parentRoute: typeof ModuleRoute
    }
    '/content/': {
      id: '/content/'
      path: '/'
      fullPath: '/content/'
      preLoaderRoute: typeof ContentIndexRouteImport
      parentRoute: typeof ContentRoute
    }
    '/track/$trackId': {
      id: '/track/$trackId'
      path: '/track/$trackId'
      fullPath: '/track/$trackId'
      preLoaderRoute: typeof TrackTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-edit/$trackId': {
      id: '/track-edit/$trackId'
      path: '/track-edit/$trackId'
      fullPath: '/track-edit/$trackId'
      preLoaderRoute: typeof TrackEditTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/module/$moduleId': {
      id: '/module/$moduleId'
      path: '/$moduleId'
      fullPath: '/module/$moduleId'
      preLoaderRoute: typeof ModuleModuleIdRouteImport
      parentRoute: typeof ModuleRoute
    }
    '/module-edit/$moduleId': {
      id: '/module-edit/$moduleId'
      path: '/module-edit/$moduleId'
      fullPath: '/module-edit/$moduleId'
      preLoaderRoute: typeof ModuleEditModuleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$contentId': {
      id: '/content/$contentId'
      path: '/$contentId'
      fullPath: '/content/$contentId'
      preLoaderRoute: typeof ContentContentIdRouteImport
      parentRoute: typeof ContentRoute
    }
    '/track/$trackId/': {
      id: '/track/$trackId/'
      path: '/'
      fullPath: '/track/$trackId/'
      preLoaderRoute: typeof TrackTrackIdIndexRouteImport
      parentRoute: typeof TrackTrackIdRoute
    }
    '/module/$moduleId/': {
      id: '/module/$moduleId/'
      path: '/'
      fullPath: '/module/$moduleId/'
      preLoaderRoute: typeof ModuleModuleIdIndexRouteImport
      parentRoute: typeof ModuleModuleIdRoute
    }
    '/content/$contentId/': {
      id: '/content/$contentId/'
      path: '/'
      fullPath: '/content/$contentId/'
      preLoaderRoute: typeof ContentContentIdIndexRouteImport
      parentRoute: typeof ContentContentIdRoute
    }
    '/content/$contentId/edit': {
      id: '/content/$contentId/edit'
      path: '/edit'
      fullPath: '/content/$contentId/edit'
      preLoaderRoute: typeof ContentContentIdEditRouteImport
      parentRoute: typeof ContentContentIdRoute
    }
    '/module/$moduleId/content/$contentId': {
      id: '/module/$moduleId/content/$contentId'
      path: '/content/$contentId'
      fullPath: '/module/$moduleId/content/$contentId'
      preLoaderRoute: typeof ModuleModuleIdContentContentIdRouteImport
      parentRoute: typeof ModuleModuleIdRoute
    }
  }
}

interface ContentContentIdRouteChildren {
  ContentContentIdEditRoute: typeof ContentContentIdEditRoute
  ContentContentIdIndexRoute: typeof ContentContentIdIndexRoute
}

const ContentContentIdRouteChildren: ContentContentIdRouteChildren = {
  ContentContentIdEditRoute: ContentContentIdEditRoute,
  ContentContentIdIndexRoute: ContentContentIdIndexRoute,
}

const ContentContentIdRouteWithChildren =
  ContentContentIdRoute._addFileChildren(ContentContentIdRouteChildren)

interface ContentRouteChildren {
  ContentContentIdRoute: typeof ContentContentIdRouteWithChildren
  ContentIndexRoute: typeof ContentIndexRoute
}

const ContentRouteChildren: ContentRouteChildren = {
  ContentContentIdRoute: ContentContentIdRouteWithChildren,
  ContentIndexRoute: ContentIndexRoute,
}

const ContentRouteWithChildren =
  ContentRoute._addFileChildren(ContentRouteChildren)

interface ModuleModuleIdRouteChildren {
  ModuleModuleIdIndexRoute: typeof ModuleModuleIdIndexRoute
  ModuleModuleIdContentContentIdRoute: typeof ModuleModuleIdContentContentIdRoute
}

const ModuleModuleIdRouteChildren: ModuleModuleIdRouteChildren = {
  ModuleModuleIdIndexRoute: ModuleModuleIdIndexRoute,
  ModuleModuleIdContentContentIdRoute: ModuleModuleIdContentContentIdRoute,
}

const ModuleModuleIdRouteWithChildren = ModuleModuleIdRoute._addFileChildren(
  ModuleModuleIdRouteChildren,
)

interface ModuleRouteChildren {
  ModuleModuleIdRoute: typeof ModuleModuleIdRouteWithChildren
  ModuleIndexRoute: typeof ModuleIndexRoute
}

const ModuleRouteChildren: ModuleRouteChildren = {
  ModuleModuleIdRoute: ModuleModuleIdRouteWithChildren,
  ModuleIndexRoute: ModuleIndexRoute,
}

const ModuleRouteWithChildren =
  ModuleRoute._addFileChildren(ModuleRouteChildren)

interface TrackTrackIdRouteChildren {
  TrackTrackIdIndexRoute: typeof TrackTrackIdIndexRoute
}

const TrackTrackIdRouteChildren: TrackTrackIdRouteChildren = {
  TrackTrackIdIndexRoute: TrackTrackIdIndexRoute,
}

const TrackTrackIdRouteWithChildren = TrackTrackIdRoute._addFileChildren(
  TrackTrackIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContentRoute: ContentRouteWithChildren,
  ContentCreateRoute: ContentCreateRoute,
  ContentEditRoute: ContentEditRoute,
  DashboardRoute: DashboardRoute,
  ModuleRoute: ModuleRouteWithChildren,
  ModuleCreateRoute: ModuleCreateRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignUpRoute: SignUpRoute,
  TrackCreateRoute: TrackCreateRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  ModuleEditModuleIdRoute: ModuleEditModuleIdRoute,
  TrackEditTrackIdRoute: TrackEditTrackIdRoute,
  TrackTrackIdRoute: TrackTrackIdRouteWithChildren,
  TrackIndexRoute: TrackIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
